"""Environment configuration and the vLLM LLM factory for the AI service."""
from __future__ import annotations

import os
from pathlib import Path

from crewai import LLM
from dotenv import load_dotenv

from web_api import config as _web_config

load_dotenv()

_TRUTHY = ("1", "true", "yes", "on")


def _env_flag(name: str) -> bool:
    """Whether the environment variable ``name`` is set to a truthy value."""
    return os.getenv(name, "false").lower() in _TRUTHY


PROJECT_ROOT = Path(__file__).resolve().parents[4]

VLLM_BASE_URL = os.getenv("VLLM_BASE_URL", "http://localhost:8000/v1")
VLLM_MODEL = os.getenv("VLLM_MODEL", "hosted_vllm/google/gemma-4-E4B-it")
VLLM_API_KEY = os.getenv("VLLM_API_KEY", "not-needed")
VLLM_MAX_TOKENS = int(os.getenv("VLLM_MAX_TOKENS", "8192"))
VLLM_TIMEOUT = int(os.getenv("VLLM_TIMEOUT", "120"))

VLLM_TEMPERATURE = float(os.getenv("VLLM_TEMPERATURE", "0.0"))
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")

QDRANT_HOST = os.getenv("QDRANT_HOST", "localhost")
QDRANT_PORT = int(os.getenv("QDRANT_PORT", "6333"))

BUYER_NAME = os.getenv("BUYER_NAME", "")
BUYER_WEBSITE = os.getenv("BUYER_WEBSITE", "")
WEB_CONTEXT_CACHE_DIR = os.getenv(
    "WEB_CONTEXT_CACHE_DIR", str(PROJECT_ROOT / "data" / "web_cache")
)
PRODUCT_SEARCH_MAX_RESULTS = int(os.getenv("PRODUCT_SEARCH_MAX_RESULTS", "3"))
SUPPLIER_SITE_SEARCH_RESULTS = int(os.getenv("SUPPLIER_SITE_SEARCH_RESULTS", "10"))

VENDOR_ENRICHMENT_ENABLED = _env_flag("VENDOR_ENRICHMENT_ENABLED")
SUPPLIER_CRAWL_ENABLED = _env_flag("SUPPLIER_CRAWL_ENABLED")
SUPPLIER_CRAWL_MAX_PAGES = int(os.getenv("SUPPLIER_CRAWL_MAX_PAGES", "3"))
SUPPLIER_CRAWL_TIMEOUT_S = int(os.getenv("SUPPLIER_CRAWL_TIMEOUT_S", "20"))
SUPPLIER_CRAWL_MAX_CHARS = int(os.getenv("SUPPLIER_CRAWL_MAX_CHARS", "8000"))
COMPANY_RESEARCH_ENABLED = os.getenv("COMPANY_RESEARCH_ENABLED", "true").lower() in _TRUTHY
COMPANY_RESEARCH_BATCH = int(os.getenv("COMPANY_RESEARCH_BATCH", "2"))

EMISSION_AGENT_ENABLED = os.getenv("EMISSION_AGENT_ENABLED", "true").lower() in _TRUTHY
EMISSION_AGENT_MAX_ITER = int(os.getenv("EMISSION_AGENT_MAX_ITER", "6"))
EMISSION_AGENT_TIMEOUT_S = int(os.getenv("EMISSION_AGENT_TIMEOUT_S", "120"))
EMISSION_SEARCH_RESULTS = int(os.getenv("EMISSION_SEARCH_RESULTS", "8"))
EMISSION_FALLBACK_CANDIDATES = int(os.getenv("EMISSION_FALLBACK_CANDIDATES", "12"))

CATEGORY_RETRIEVAL_ENABLED = _env_flag("CATEGORY_RETRIEVAL_ENABLED")
CATEGORY_RETRIEVAL_TOP_K = int(os.getenv("CATEGORY_RETRIEVAL_TOP_K", "5"))

CHART_OF_ACCOUNTS_PATH = os.getenv(
    "CHART_OF_ACCOUNTS_PATH", str(PROJECT_ROOT / "data" / "chart_of_accounts.csv")
)
INVOICES_DIR = os.getenv("INVOICES_DIR", str(PROJECT_ROOT / "data" / "invoices"))
LEDGER_PATH = os.getenv("LEDGER_PATH", str(PROJECT_ROOT / "output" / "ledger.csv"))
CHROMA_DIR = os.getenv("CHROMA_DIR", str(PROJECT_ROOT / "chroma_db"))

INVOICE_CONCURRENCY = int(os.getenv("INVOICE_CONCURRENCY", "4"))

DOC_MAX_ATTEMPTS = int(os.getenv("DOC_MAX_ATTEMPTS", "3"))

DOC_RECONCILE_TOLERANCE_PCT = _web_config.DOC_RECONCILE_TOLERANCE_PCT
DOC_RECONCILE_TOLERANCE_ABS = _web_config.DOC_RECONCILE_TOLERANCE_ABS
DOC_INTERNAL_TOLERANCE_PCT = _web_config.DOC_INTERNAL_TOLERANCE_PCT
DOC_INTERNAL_TOLERANCE_ABS = _web_config.DOC_INTERNAL_TOLERANCE_ABS

DOC_STALE_CLAIM_MINUTES = int(os.getenv("DOC_STALE_CLAIM_MINUTES", "60"))

DOC_VISION_MAX_PAGES = int(os.getenv("DOC_VISION_MAX_PAGES", "8"))

DOC_VISION_MAX_EDGE = int(os.getenv("DOC_VISION_MAX_EDGE", "1600"))

DOC_VISION_PAGE_BANDS = int(os.getenv("DOC_VISION_PAGE_BANDS", "3"))

DOC_VISION_MAX_IMAGES = int(os.getenv("DOC_VISION_MAX_IMAGES", "12"))

AGREEMENT_HEADER_PAGES = int(os.getenv("AGREEMENT_HEADER_PAGES", "3"))
AGREEMENT_VISION_MAX_PAGES = int(os.getenv("AGREEMENT_VISION_MAX_PAGES", "20"))
AGREEMENT_MAX_ATTEMPTS = int(os.getenv("AGREEMENT_MAX_ATTEMPTS", "3"))
AGREEMENT_STALE_CLAIM_MINUTES = int(os.getenv("AGREEMENT_STALE_CLAIM_MINUTES", "60"))
AGREEMENT_SCOPE_CATEGORIES = int(os.getenv("AGREEMENT_SCOPE_CATEGORIES", "3"))
AGREEMENT_SIMILARITY_MIN = float(os.getenv("AGREEMENT_SIMILARITY_MIN", "0.35"))
AGREEMENT_CANDIDATES_MAX = int(os.getenv("AGREEMENT_CANDIDATES_MAX", "5000"))
AGREEMENT_JUDGE_BATCH = int(os.getenv("AGREEMENT_JUDGE_BATCH", "8"))
AGREEMENT_JUDGE_CONCURRENCY = int(os.getenv("AGREEMENT_JUDGE_CONCURRENCY", "4"))
AGREEMENT_PAGE_SIZE = int(os.getenv("AGREEMENT_PAGE_SIZE", "2000"))
AGREEMENT_WATERMARK_MARGIN_MINUTES = int(os.getenv("AGREEMENT_WATERMARK_MARGIN_MINUTES", "10"))
AGREEMENT_PRICE_TOLERANCE_PCT = float(os.getenv("AGREEMENT_PRICE_TOLERANCE_PCT", "1.0"))
AGREEMENT_DISCOUNT_TOLERANCE_PCT = float(os.getenv("AGREEMENT_DISCOUNT_TOLERANCE_PCT", "0.5"))

ALTERNATIVES_SCAN_ENABLED = os.getenv("ALTERNATIVES_SCAN_ENABLED", "false").lower() in _TRUTHY
ALTERNATIVES_SCAN_INTERVAL_HOURS = int(os.getenv("ALTERNATIVES_SCAN_INTERVAL_HOURS", "24"))
ALTERNATIVES_SCAN_ITEMS = int(os.getenv("ALTERNATIVES_SCAN_ITEMS", "50"))
ALTERNATIVES_RESCAN_DAYS = int(os.getenv("ALTERNATIVES_RESCAN_DAYS", "30"))
ALTERNATIVES_MIN_SAVING_PERCENT = float(os.getenv("ALTERNATIVES_MIN_SAVING_PERCENT", "3"))
ALTERNATIVES_EQUAL_TOLERANCE_PERCENT = float(os.getenv("ALTERNATIVES_EQUAL_TOLERANCE_PERCENT", "2"))
ALTERNATIVES_SPEC_BATCH = int(os.getenv("ALTERNATIVES_SPEC_BATCH", "8"))
ALTERNATIVES_SPEC_CONCURRENCY = int(os.getenv("ALTERNATIVES_SPEC_CONCURRENCY", "4"))
ALTERNATIVES_SPEC_MAX_FAILURES = int(os.getenv("ALTERNATIVES_SPEC_MAX_FAILURES", "3"))
ALTERNATIVES_SPEC_MIN_CONFIDENCE = float(os.getenv("ALTERNATIVES_SPEC_MIN_CONFIDENCE", "0.5"))
ALTERNATIVES_SIMILAR = int(os.getenv("ALTERNATIVES_SIMILAR", "20"))
ALTERNATIVES_SIMILARITY_MIN = float(os.getenv("ALTERNATIVES_SIMILARITY_MIN", "0.6"))
ALTERNATIVES_OFFER_TTL_DAYS = int(os.getenv("ALTERNATIVES_OFFER_TTL_DAYS", "14"))
ALTERNATIVES_QUERIES_PER_ITEM = int(os.getenv("ALTERNATIVES_QUERIES_PER_ITEM", "2"))
ALTERNATIVES_PAGES_PER_ITEM = int(os.getenv("ALTERNATIVES_PAGES_PER_ITEM", "4"))
ALTERNATIVES_HOST_INTERVAL_S = float(os.getenv("ALTERNATIVES_HOST_INTERVAL_S", "5"))
ALTERNATIVES_PAGE_CHARS = int(os.getenv("ALTERNATIVES_PAGE_CHARS", "6000"))
ALTERNATIVES_PAGE_TIMEOUT_S = int(os.getenv("ALTERNATIVES_PAGE_TIMEOUT_S", "20"))
ALTERNATIVES_SHOPS_ENABLED = os.getenv("ALTERNATIVES_SHOPS_ENABLED", "true").lower() in _TRUTHY
ALTERNATIVES_WEB_ENABLED = os.getenv("ALTERNATIVES_WEB_ENABLED", "true").lower() in _TRUTHY
ALTERNATIVES_SHOPS_FILE = os.getenv("ALTERNATIVES_SHOPS_FILE", "")
SEARXNG_URL = os.getenv("SEARXNG_URL", "")
SEARXNG_ENGINES = os.getenv("SEARXNG_ENGINES", "google,bing,brave,duckduckgo")
BENCHMARK_MIN_ORGANIZATIONS = max(3, int(os.getenv("BENCHMARK_MIN_ORGANIZATIONS", "3")))
FARNELL_API_KEY = os.getenv("FARNELL_API_KEY", "")
MOUSER_API_KEY = os.getenv("MOUSER_API_KEY", "")
DIGIKEY_CLIENT_ID = os.getenv("DIGIKEY_CLIENT_ID", "")
DIGIKEY_CLIENT_SECRET = os.getenv("DIGIKEY_CLIENT_SECRET", "")

WORKER_POLL_SECONDS = float(os.getenv("WORKER_POLL_SECONDS", "5"))

WORKER_DOCUMENT_BATCH = int(os.getenv("WORKER_DOCUMENT_BATCH", "5"))


def get_llm() -> LLM:
    """Return a CrewAI LLM pointed at the local vLLM OpenAI-compatible endpoint."""
    return LLM(
        model=VLLM_MODEL,
        base_url=VLLM_BASE_URL,
        api_key=VLLM_API_KEY,
        max_tokens=VLLM_MAX_TOKENS,
        timeout=VLLM_TIMEOUT,
        temperature=VLLM_TEMPERATURE,
    )
